### ISSUE TITLE
Error when trying to import some data in betAS

### ISSUE THREAD

**Issue by evaesquinas** [marianaferreira/betAS#12]
To whom it may concern,

I am interested in using your app server betAS (https://compbio.imm.medicina.ulisboa.pt/app/betAS) with the output from vast-tools but I am having problems importing the data. I have tried to upload the inclusion levels' file obtained from vast-tools without success as it appears the following error "Maximum upload size exceeded". Find attached a screenshot with the error.
**The size of the file 559MB.

![inclusionLevels](https://github.com/DiseaseTranscriptomicsLab/compbio-app-server/assets/78473997/de7b70f1-8c08-49fa-9214-0dc0e5a4e98f)

On the other hand, if I try to upload the "DIFFAS" file (output obtained after vast-tools compare) whose size is in KB... it is uploaded without no problems. Find attached a screenshot of this case.

![diffas](https://github.com/DiseaseTranscriptomicsLab/compbio-app-server/assets/78473997/dd88f0de-0afc-44e4-9096-0e1eafc2ff02)

Is there any possibility to upload the inclusion levels tables? Do I have to make a transformation of the file or reduce it in some way? Any feedback will be well-received.

Thanks very much in advance.

Kind Regards

**Comment by marianaferreira** [comment]
Dear Eva,

Thank you for reaching out. We appreciate your interest in using betAS and the time you took to detail the issue you encountered.

The limitation on file sizes to 100Mb in the compbio.imm.medicina.ulisboa.pt app server is currently in place due to internal restrictions. While we are considering expanding this limit in the future, for now, it remains at a maximum of 100Mb.

We would firstly suggest that, when using vast-tools, consider limiting the types of events you are analysing, such as by focusing only on exon skipping or intron retention events. This can help reduce the file size.

However, if you intend to use your original file, we suggest a couple of alternatives:

1. Compress Your .tab File:
Attempt to compress your .tab file (the output of vast-tools), as it might contain redundant information that can significantly reduce the file size.

2. Local Usage:
If compression doesn't resolve the issue, you can run betAS locally on your computer. Follow these steps:
- Download the latest stable release of betAS (currently v1.1.0) from [here](https://github.com/DiseaseTranscriptomicsLab/betAS/archive/refs/tags/v1.1.0.zip).
- Extract the files and locate the `betAS.R` script in the 'R' folder.
- Run the `betAS.R` script using RStudio. This should launch the web app.
- To modify the file size limit, adjust the value of `shiny.maxRequestSize` (currently set to 100Mb). Keep in mind that larger files may take longer to load. Consider uploading compressed files (gz) for efficiency.

3. R Package Usage:
If the above options aren't feasible, consider running betAS as an R package. Refer to the tutorial [here](https://diseasetranscriptomicslab.github.io/betAS/inst/betAS_tutorial.html) for guidance. While this approach doesn't provide the visual interface, it allows access to the same functionalities.

Regarding the point you raised about the DIFFAS file, for vast-tools’ input files betAS specifically works with “INCLUSION_LEVELS” tables as input (obtained with vast-tools combine) and, while the outputs of other vast-tools modules (such as compare or diff) may be properly read, these do not provide the required information and thus are not compatible with the following steps of betAS analyses. We appreciate your observation and will update the app and readme to clarify the supported file types.

We apologize for any inconvenience this may have caused. Your feedback is valuable, and we are committed to improving the clarity of our documentation. Please feel free to reach out if you have further questions or need assistance.

Best,
Mariana

**Comment by evaesquinas** [comment]
Dear Mariana,

Thanks a lot for your detailed answer and clarification. I really appreciate it. I will try the approaches that you have mentioned and I will contact you again in case I have problems. 
For now, I do not have anything else to add to this issue, cause I need some time to try it and play with the data. However, I realised that you transfered the issue to another sub-repository. I did not know that betAS had its own repository because the link that it appears in the server https://compbio.imm.medicina.ulisboa.pt/app/betAS is the "compbio-app-server" (https://github.com/DiseaseTranscriptomicsLab/compbio-app-server). Morever, I would like to mention that before I posted the issue here, I tried to contact via email (imm-nmorais@medicina.ulisboa.pt, the one that appears in the server) and I received this error: 

```
Erro na entrega a estes destinatarios ou grupos:

[imm-nmorais@medicina.ulisboa.pt (UNDEFINED:imm-nmorais@medicina.ulisboa.pt)](mailto:IMCEAUNDEFINED-imm-nmorais%2B40medicina%2B2Eulisboa%2B2Ept@eurprd04.prod.outlook.com)
Produciuse un problema durante a entrega da túa mensaxe porque non hai un conector de saída adecuado para controlar este tipo de enderezo de correo electrónico de destinatario.
```

As you mentioned that you were going to update the app and documentation... it would be very helpful if you update those things too. 

Thanks again for your feedback and help.

Regards
